os: linux
dist: jammy

jobs:
  include:
    - name: "job one"
      vm: 
        create:
          name: 16june_100k_02
      script: 
        - echo "condition with job tes1"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
